/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package klinikbersalinjavaapp;

import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Farkhanz
 */
public class DaftarPemeriksaan extends javax.swing.JFrame {
    // Code function atur tanggal    
    java.util.Date saatini = new java.util.Date();
    private SimpleDateFormat simpdafo = new SimpleDateFormat("dd MMMMMMMMM yyyy", Locale.getDefault());
    private String tanggal = simpdafo.format(saatini);
    private Connection conn;
    private Statement state;

    /**
     * Creates new form DaftarPemeriksaan
     */
    public DaftarPemeriksaan() {
        initComponents();
        setLocationRelativeTo(this);
        TglSaatIni.setText(tanggal);
        setJam();
    }
    
        // Code function atur waktu   
        public final void setJam(){
        ActionListener taskPerformer = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String jam = "", menit = "", detik = "";
                
                java.util.Date Waktu = new java.util.Date();
                int set_jam = Waktu.getHours();
                int set_menit = Waktu.getMinutes();
                int set_detik = Waktu.getSeconds();
                
                if(set_jam <= 9) jam= "0";
                if(set_menit <= 9) menit= "0";
                if(set_detik <= 9) detik= "0";
                
                String hours = jam + Integer.toString(set_jam);
                String minutes = menit + Integer.toString(set_menit);
                String seconds = detik + Integer.toString(set_detik);
                
                wkt1.setText(hours+":"+minutes+":"+seconds);
            }
        };
        new Timer(1000, taskPerformer).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        TanggaLabel2 = new javax.swing.JLabel();
        TglSaatIni = new javax.swing.JLabel();
        WaktuLabel2 = new javax.swing.JLabel();
        wkt1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btsimpan = new javax.swing.JButton();
        DaftarBaru = new javax.swing.JButton();
        BatalDaftar = new javax.swing.JButton();
        Keluar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        InputNoDaftar = new javax.swing.JTextField();
        InputRekamMedis = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        InputNamaPasien = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        InputAlamat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        InputTelp = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ComboTindakan = new javax.swing.JComboBox<>();
        CariRekamMedis = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Traditional Arabic", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PENDAFTARAN");
        jDesktopPane1.add(jLabel1);
        jLabel1.setBounds(180, 10, 150, 26);

        TanggaLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        TanggaLabel2.setText("Tanggal :");

        TglSaatIni.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        TglSaatIni.setText("Tanggal :");

        WaktuLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        WaktuLabel2.setText("Waktu :");

        wkt1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        wkt1.setText("Waktu :");

        btsimpan.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btsimpan.setText("Daftar");
        btsimpan.setToolTipText("Daftar Periksa");
        btsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsimpanActionPerformed(evt);
            }
        });

        DaftarBaru.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        DaftarBaru.setText("Pasien Baru");
        DaftarBaru.setToolTipText("Buat Pasien Baru");
        DaftarBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DaftarBaruActionPerformed(evt);
            }
        });

        BatalDaftar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BatalDaftar.setText("Batal Daftar");
        BatalDaftar.setToolTipText("Batal Pendaftaran");
        BatalDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BatalDaftarActionPerformed(evt);
            }
        });

        Keluar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Keluar.setText("Keluar");
        Keluar.setToolTipText("Keluar");
        Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("No Daftar");

        InputNoDaftar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        InputRekamMedis.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("No. Rekam Medis");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Nama Pasien");

        InputNamaPasien.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Alamat");

        InputAlamat.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("No. Telp");

        InputTelp.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("Pemeriksaan");

        ComboTindakan.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        ComboTindakan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "== :::: PILIH TINDAKAN ::::==", "KB", "IMUNISASI", "PERIKSA KEHAMILAN", "PERSALINAN ", "PEMERIKSAAN ANAK" }));

        CariRekamMedis.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CariRekamMedis.setText("Cari");
        CariRekamMedis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CariRekamMedisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InputNamaPasien)
                    .addComponent(InputAlamat)
                    .addComponent(InputTelp)
                    .addComponent(ComboTindakan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(InputNoDaftar, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(InputRekamMedis, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CariRekamMedis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(InputNoDaftar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputRekamMedis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(CariRekamMedis))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(InputNamaPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(InputAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ComboTindakan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Keluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DaftarBaru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BatalDaftar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DaftarBaru, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BatalDaftar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TanggaLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TglSaatIni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(WaktuLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(wkt1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TglSaatIni)
                    .addComponent(TanggaLabel2)
                    .addComponent(wkt1)
                    .addComponent(WaktuLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsimpanActionPerformed
        String no_daftar = InputNoDaftar.getText();
        String tanggal = TglSaatIni.getText();
        String jam = wkt1.getText();
        String no_rm = InputRekamMedis.getText();
        String nama = InputNamaPasien.getText();
        String periksa = (String) ComboTindakan.getSelectedItem();
        {
        try
        {
        Class.forName("com.mysql.jdbc.Driver").newInstance();
        com.mysql.jdbc.Connection conn = (com.mysql.jdbc.Connection) DriverManager.getConnection(
        "jdbc:mysql://localhost:3306/klinik_db", "root", "");
        com.mysql.jdbc.Statement state = (com.mysql.jdbc.Statement) conn.createStatement();
        String sql="insert into daftar values('"+no_daftar+"','"+tanggal+"','"+jam+"','"+no_rm+"','"+nama+"','"+periksa+"')";
        int executeUpdate = state.executeUpdate(sql);
        state.close();
        JOptionPane.showMessageDialog(null, "Anda Telah Terdaftar..","Insert Data",JOptionPane.INFORMATION_MESSAGE);
        InputNoDaftar.setText("");
        InputRekamMedis.setText("");
        InputNamaPasien.setText("");
        InputAlamat.setText("");
        InputTelp.setText("");
        ComboTindakan.setSelectedItem("");
        //txtnpm.setFocusable(rootPaneCheckingEnabled);
        conn.close();
        }
        catch (     ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e)
        {
        JOptionPane.showMessageDialog(null, "Eror: "+e,"Gagal",JOptionPane.WARNING_MESSAGE);
        //System.err.println("Exception: "+e.getMessage());
        }
            }
    }//GEN-LAST:event_btsimpanActionPerformed

    private void DaftarBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DaftarBaruActionPerformed
        new DataPasien().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_DaftarBaruActionPerformed

    private void BatalDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BatalDaftarActionPerformed
        InputNoDaftar.setText("");
        InputRekamMedis.setText("");
        InputNamaPasien.setText("");
        InputAlamat.setText("");
        InputTelp.setText("");
        ComboTindakan.setSelectedItem("== :::: PILIH TINDAKAN ::::==");
    }//GEN-LAST:event_BatalDaftarActionPerformed

    private void KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarActionPerformed
        new MenuUtama().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_KeluarActionPerformed

    private void CariRekamMedisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CariRekamMedisActionPerformed
        String no_rm = InputRekamMedis.getText();
        try
        {
        Class.forName("com.mysql.jdbc.Driver").newInstance();
        com.mysql.jdbc.Connection conn = (com.mysql.jdbc.Connection) DriverManager.getConnection(
        "jdbc:mysql://localhost:3306/klinik_db", "root", "");
        com.mysql.jdbc.Statement statement = (com.mysql.jdbc.Statement) conn.createStatement();
        String sql="SELECT * FROM pasien WHERE no_rm like '"+no_rm+"'";
         ResultSet view = statement.executeQuery(sql);
        if (view.next())
        {
        InputNamaPasien.setText(view.getString(2));
        InputAlamat.setText(view.getString(7));
        InputTelp.setText(view.getString(8));
        JOptionPane.showMessageDialog(null, "Data ditemukan","Insert Data",JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
        JOptionPane.showMessageDialog(null, "Data tidak ditemukan ","Insert Data",JOptionPane.INFORMATION_MESSAGE);
        }
        statement.close();
        conn.close();
        }
        catch ( ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e)
        {
        JOptionPane.showMessageDialog(null, "Eror:"+e,"Gagal",JOptionPane.WARNING_MESSAGE);
        //System.err.println("Exception: "+e.getMessage());
        }
    }//GEN-LAST:event_CariRekamMedisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DaftarPemeriksaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DaftarPemeriksaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DaftarPemeriksaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DaftarPemeriksaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DaftarPemeriksaan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BatalDaftar;
    private javax.swing.JButton CariRekamMedis;
    private javax.swing.JComboBox<String> ComboTindakan;
    private javax.swing.JButton DaftarBaru;
    private javax.swing.JTextField InputAlamat;
    private javax.swing.JTextField InputNamaPasien;
    private javax.swing.JTextField InputNoDaftar;
    private javax.swing.JTextField InputRekamMedis;
    private javax.swing.JTextField InputTelp;
    private javax.swing.JButton Keluar;
    private javax.swing.JLabel TanggaLabel2;
    private javax.swing.JLabel TglSaatIni;
    private javax.swing.JLabel WaktuLabel2;
    private javax.swing.JButton btsimpan;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel wkt1;
    // End of variables declaration//GEN-END:variables
    
    private void nyala (boolean x){
        InputNamaPasien.setEditable(x);
        InputAlamat.setEditable(x);
        InputTelp.setEditable(x);
        InputNoDaftar.requestFocus();
    }

}
