/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package klinikbersalinjavaapp;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.awt.HeadlessException;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Farkhanz
 */
public class DataObat extends javax.swing.JFrame {

    /**
     * Creates new form DataObat
     */
    public DataObat() {
        initComponents();
        setLocationRelativeTo(this);
        nyala(false);
        btnSet(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LabelObat = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        InputKdObat = new javax.swing.JTextField();
        CariObat = new javax.swing.JButton();
        InputNamaObat = new javax.swing.JTextField();
        ComboJenObat = new javax.swing.JComboBox<>();
        ComboSatuan = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        InputHargaObat = new javax.swing.JTextField();
        InputStockObat = new javax.swing.JTextField();
        InputStockMin = new javax.swing.JTextField();
        InputSuplier = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TambahObat = new javax.swing.JButton();
        KeluarObat = new javax.swing.JButton();
        SimpanObat = new javax.swing.JButton();
        EditObat = new javax.swing.JButton();
        BatalObat = new javax.swing.JButton();
        HapusObat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));

        LabelObat.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        LabelObat.setForeground(new java.awt.Color(255, 255, 255));
        LabelObat.setText("DATA OBAT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(LabelObat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(LabelObat)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Kode Obat");

        InputKdObat.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        CariObat.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        CariObat.setText("Cari");
        CariObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CariObatActionPerformed(evt);
            }
        });

        InputNamaObat.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        ComboJenObat.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ComboJenObat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "= Pilih Jenis Obat=", "Tablet", "Syrup", "Puyer", "Kapsul", "Pil" }));

        ComboSatuan.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ComboSatuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "== Pilih Satuan==", "Pcs", "Box", "Botol", "Strip", "doos" }));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Nama Obat");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Jenis Obat");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Satuan");

        InputHargaObat.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        InputStockObat.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        InputStockMin.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        InputSuplier.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Harga");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Stock");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("Stock. Min");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setText("Suplier");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComboJenObat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(InputKdObat, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CariObat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(InputNamaObat)
                    .addComponent(ComboSatuan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(InputHargaObat, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(InputStockObat)
                    .addComponent(InputStockMin)
                    .addComponent(InputSuplier))
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(InputKdObat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CariObat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputNamaObat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboJenObat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputHargaObat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputStockObat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputStockMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputSuplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        TambahObat.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        TambahObat.setText("Tambah");
        TambahObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahObatActionPerformed(evt);
            }
        });

        KeluarObat.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        KeluarObat.setText("Keluar");
        KeluarObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarObatActionPerformed(evt);
            }
        });

        SimpanObat.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        SimpanObat.setText("Simpan");
        SimpanObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanObatActionPerformed(evt);
            }
        });

        EditObat.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        EditObat.setText("Edit");
        EditObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditObatActionPerformed(evt);
            }
        });

        BatalObat.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BatalObat.setText("Batal");
        BatalObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BatalObatActionPerformed(evt);
            }
        });

        HapusObat.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        HapusObat.setText("Hapus");
        HapusObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusObatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(HapusObat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TambahObat, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BatalObat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SimpanObat, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EditObat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(KeluarObat, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TambahObat)
                    .addComponent(SimpanObat)
                    .addComponent(EditObat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HapusObat)
                    .addComponent(BatalObat)
                    .addComponent(KeluarObat))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TambahObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahObatActionPerformed
        nyala(true);
        btnSet(false);
    }//GEN-LAST:event_TambahObatActionPerformed

    private void KeluarObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarObatActionPerformed
        new MenuUtama().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_KeluarObatActionPerformed

    private void SimpanObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanObatActionPerformed
        // Simpan Data Obat
        String kode_obat = InputKdObat.getText();
        String nama_obat = InputNamaObat.getText();
        String jenis = (String) ComboJenObat.getSelectedItem();
        String satuan = (String) ComboSatuan.getSelectedItem();
        String harga = InputHargaObat.getText();
        String stok = InputStockObat.getText();
        String stokmin = InputStockMin.getText();
        String suplier = InputSuplier.getText();

        {
        try
        {
        Class.forName("com.mysql.jdbc.Driver").newInstance();
        Connection conn = (Connection) DriverManager.getConnection(
        "jdbc:mysql://localhost:3306/klinik_db", "root", "");
        Statement state = (Statement) conn.createStatement();
        String sql="insert into obat values('"+kode_obat+"','"+nama_obat+"','"+jenis+"','"+satuan+"','"+harga+"','"+stok+"','"+stokmin+"','"+suplier+"')";
        int executeUpdate = state.executeUpdate(sql);
        state.close();
        JOptionPane.showMessageDialog(null, "Data berhasil dimasukkan..","Insert Data",JOptionPane.INFORMATION_MESSAGE);
        nyala(true);
        InputKdObat.setText("");
        InputNamaObat.setText("");
        ComboJenObat.setSelectedItem("= Pilih Jenis Obat=");
        ComboSatuan.setSelectedItem("== Pilih Satuan==");
        InputHargaObat.setText("");
        InputStockObat.setText("");
        InputStockMin.setText("");
        InputSuplier.setText("");
        //txtnpm.setFocusable(rootPaneCheckingEnabled);
        conn.close();
        }
        catch (     ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e)
        {
        JOptionPane.showMessageDialog(null, "Eror: "+e,"Gagal",JOptionPane.WARNING_MESSAGE);
        //System.err.println("Exception: "+e.getMessage());
        }
            }
    }//GEN-LAST:event_SimpanObatActionPerformed

    private void EditObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditObatActionPerformed
        String kode_obat = InputKdObat.getText();
        String nama_obat = InputNamaObat.getText();
        String jenis = (String) ComboJenObat.getSelectedItem();
        String satuan = (String) ComboSatuan.getSelectedItem();
        String harga = InputHargaObat.getText();
        String stok = InputStockObat.getText();
        String stokmin = InputStockMin.getText();
        String suplier = InputSuplier.getText();

        try {
        Class.forName("com.mysql.jdbc.Driver").newInstance();
        Connection conn = (Connection) DriverManager.getConnection(
        "jdbc:mysql://localhost:3306/klinik_db", "root", "");
        Statement state = (Statement) conn.createStatement();
        String sql="UPDATE obat SET NAMA_OBAT='"+nama_obat+"',JENIS='"+jenis+"',SATUAN='"+satuan+"',HARGA='"+harga+"',STOK='"+stok+"',STOKMIN='"+stokmin+"',SUPLIER='"+suplier+"' WHERE kode_obat LIKE '"+kode_obat+"'";
        state.executeUpdate(sql);
        state.close();
        JOptionPane.showMessageDialog(null, "Data berhasil diedit..","Insert Data",JOptionPane.INFORMATION_MESSAGE);
        conn.close();
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e) {
        JOptionPane.showMessageDialog(null, "Eror: "+e,"Gagal",JOptionPane.WARNING_MESSAGE);
        //System.err.println("Exception: "+e.getMessage());
        }
    }//GEN-LAST:event_EditObatActionPerformed

    private void BatalObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BatalObatActionPerformed
        InputKdObat.setText("");
        InputNamaObat.setText("");
        ComboJenObat.setSelectedItem("= Pilih Jenis Obat=");
        ComboSatuan.setSelectedItem("== Pilih Satuan==");
        InputHargaObat.setText("");
        InputStockObat.setText("");
        InputStockMin.setText("");
        InputSuplier.setText("");
    }//GEN-LAST:event_BatalObatActionPerformed

    private void HapusObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusObatActionPerformed
        String kode_obat = InputKdObat.getText();
        try {
        Class.forName("com.mysql.jdbc.Driver").newInstance();
        Connection conn = (Connection) DriverManager.getConnection(
        "jdbc:mysql://localhost:3306/klinik_db", "root", "");
        Statement state = (Statement) conn.createStatement();
        String sql="DELETE FROM obat WHERE kode LIKE '"+kode_obat+"'";
        state.executeUpdate(sql);
        state.close();
        InputKdObat.setText("");
        InputNamaObat.setText("");
        ComboJenObat.setSelectedItem("");
        ComboSatuan.setSelectedItem("");
        InputHargaObat.setText("");
        InputStockObat.setText("");
        InputStockMin.setText("");
        InputSuplier.setText("");
        JOptionPane.showMessageDialog(null, "Data berhasil dihapus..","Insert Data",JOptionPane.INFORMATION_MESSAGE);
        conn.close();
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e) { JOptionPane.showMessageDialog(null, "Eror: "+e,"Gagal",JOptionPane.WARNING_MESSAGE);
        //System.err.println("Exception: "+e.getMessage());
        }
    }//GEN-LAST:event_HapusObatActionPerformed

    private void CariObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CariObatActionPerformed
        String kode_obat = InputKdObat.getText();
        try
        {
        Class.forName("com.mysql.jdbc.Driver").newInstance();
        Connection conn = (Connection) DriverManager.getConnection(
        "jdbc:mysql://localhost:3306/klinik_db", "root", "");
        Statement state = (Statement) conn.createStatement();
        String sql="SELECT * FROM obat WHERE kode_obat like '"+kode_obat+"'";
         ResultSet view = state.executeQuery(sql);
        if (view.next())
        {
        nyala(true);
        btnSet(false);
        InputNamaObat.setText(view.getString(2));
        ComboJenObat.setSelectedItem(view.getString(3));
        ComboSatuan.setSelectedItem(view.getString(4));
        InputHargaObat.setText(view.getString(5));
        InputStockObat.setText(view.getString(6));
        InputStockMin.setText(view.getString(7));
        InputSuplier.setText(view.getString(8));
        JOptionPane.showMessageDialog(null, "Data ditemukan","Insert Data",JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
        JOptionPane.showMessageDialog(null, "Data tidak ditemukan ","Insert Data",JOptionPane.INFORMATION_MESSAGE);
        }
        state.close();
        conn.close();
        }
        catch ( ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e)
        {
        JOptionPane.showMessageDialog(null, "Eror:"+e,"Gagal",JOptionPane.WARNING_MESSAGE);
        //System.err.println("Exception: "+e.getMessage());
        }
    }//GEN-LAST:event_CariObatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataObat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BatalObat;
    private javax.swing.JButton CariObat;
    private javax.swing.JComboBox<String> ComboJenObat;
    private javax.swing.JComboBox<String> ComboSatuan;
    private javax.swing.JButton EditObat;
    private javax.swing.JButton HapusObat;
    private javax.swing.JTextField InputHargaObat;
    private javax.swing.JTextField InputKdObat;
    private javax.swing.JTextField InputNamaObat;
    private javax.swing.JTextField InputStockMin;
    private javax.swing.JTextField InputStockObat;
    private javax.swing.JTextField InputSuplier;
    private javax.swing.JButton KeluarObat;
    private javax.swing.JLabel LabelObat;
    private javax.swing.JButton SimpanObat;
    private javax.swing.JButton TambahObat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
    
    private void nyala (boolean x){
//        InputKdObat.setEditable(x);
        InputNamaObat.setEditable(x);
        ComboJenObat.setEnabled(x);
        ComboSatuan.setEnabled(x);
        InputHargaObat.setEditable(x);
        InputStockObat.setEditable(x);
        InputStockMin.setEditable(x);
        InputSuplier.setEditable(x);
        InputKdObat.requestFocus();
    }
    
    private void btnSet (boolean y){
        SimpanObat.setEnabled(!y);
        EditObat.setEnabled(!y);
        HapusObat.setEnabled(!y);
        BatalObat.setEnabled(!y);
    }
}
