/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package klinikbersalinjavaapp;

import config.koneksi;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Farkhanz
 */
public class DataPasien extends javax.swing.JFrame {

    /**
     * Creates new form DataPasien
     */
    public DataPasien() {
        initComponents();
        setLocationRelativeTo(this);
        nyala(false);
        btnSet(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        NamaLabel = new javax.swing.JLabel();
        InputRm = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        RmLabel = new javax.swing.JLabel();
        InputUsia = new javax.swing.JTextField();
        InputNama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ComboJenisKel = new javax.swing.JComboBox<>();
        PekerjaanLabel = new javax.swing.JLabel();
        AlamatLabel = new javax.swing.JLabel();
        TeleponLabel = new javax.swing.JLabel();
        InputPekerjaan = new javax.swing.JTextField();
        InputAlamat = new javax.swing.JTextField();
        InputTelepon = new javax.swing.JTextField();
        ComboStats = new javax.swing.JComboBox<>();
        StatusLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Data Pasien");
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(0, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Data Pasien");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(148, 148, 148))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 505, -1));

        jPanel2.setBackground(new java.awt.Color(255, 153, 51));

        NamaLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        NamaLabel.setText("Nama");

        InputRm.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        InputRm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputRmActionPerformed(evt);
            }
        });

        btnCari.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        RmLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        RmLabel.setText("No. Rekam Medis");

        InputUsia.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        InputNama.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Usia");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Jenis Kelamin");

        ComboJenisKel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ComboJenisKel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "== PILIH JENIS KELAMIN ==", "LAKI-LAKI", "PEREMPUAN" }));

        PekerjaanLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        PekerjaanLabel.setText("Pekerjaan");

        AlamatLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        AlamatLabel.setText("Alamat");

        TeleponLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        TeleponLabel.setText("Telepon");

        InputPekerjaan.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        InputAlamat.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        InputTelepon.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        ComboStats.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ComboStats.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "== PILIH STATUS ==", "MENIKAH", "BELUM MENIKAH" }));

        StatusLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        StatusLabel.setText("Status");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RmLabel)
                    .addComponent(jLabel2)
                    .addComponent(NamaLabel)
                    .addComponent(jLabel3)
                    .addComponent(PekerjaanLabel)
                    .addComponent(AlamatLabel)
                    .addComponent(TeleponLabel)
                    .addComponent(StatusLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(InputRm, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(InputNama)
                    .addComponent(InputUsia)
                    .addComponent(ComboJenisKel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(InputPekerjaan)
                    .addComponent(InputTelepon)
                    .addComponent(InputAlamat)
                    .addComponent(ComboStats, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputRm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari)
                    .addComponent(RmLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NamaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputUsia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ComboJenisKel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboStats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StatusLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PekerjaanLabel)
                    .addComponent(InputPekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AlamatLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TeleponLabel))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 505, 400));

        btnTambah.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnSimpan.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnBatal.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnKeluar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTambah)
                    .addComponent(btnSimpan)
                    .addComponent(btnEdit))
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHapus)
                    .addComponent(btnBatal)
                    .addComponent(btnKeluar))
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InputRmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputRmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputRmActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        nyala(true);
        btnSet(false);
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        InputRm.setText("");
        InputNama.setText("");
        InputUsia.setText("");
        ComboJenisKel.setSelectedItem("== PILIH JENIS KELAMIN ==");
        ComboStats.setSelectedItem("== PILIH STATUS ==");
        InputPekerjaan.setText("");
        InputAlamat.setText("");
        InputTelepon.setText("");
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        String no_rm = InputRm.getText();
        String nama = InputNama.getText();
        String usia = InputUsia.getText();
        String jenis_kelamin = (String) ComboJenisKel.getSelectedItem();
        String status = (String) ComboStats.getSelectedItem();
        String pekerjaan = InputPekerjaan.getText();
        String alamat = InputAlamat.getText();
        String no_telp = InputTelepon.getText();
        {
        try
        {
        Class.forName("com.mysql.jdbc.Driver").newInstance();
        com.mysql.jdbc.Connection conn = (com.mysql.jdbc.Connection) DriverManager.getConnection(
        "jdbc:mysql://localhost:3306/klinik_db", "root", "");
        com.mysql.jdbc.Statement statement = (com.mysql.jdbc.Statement) conn.createStatement();
        String sql="insert into pasien values('"+no_rm+"','"+nama+"','"+usia+"','"+jenis_kelamin+"','"+status+"','"+pekerjaan+"','"+alamat+"','"+no_telp+"')";
        int executeUpdate = statement.executeUpdate(sql);
        statement.close();
        JOptionPane.showMessageDialog(null, "Data berhasil dimasukkan..","Insert Data",JOptionPane.INFORMATION_MESSAGE);
        nyala(true);
        InputRm.setText("");
        InputNama.setText("");
        InputUsia.setText("");
        ComboJenisKel.setSelectedItem("== PILIH JENIS KELAMIN ==");
        ComboStats.setSelectedItem("== PILIH STATUS ==");
        InputPekerjaan.setText("");
        InputAlamat.setText("");
        InputTelepon.setText("");
        //txtnpm.setFocusable(rootPaneCheckingEnabled);
        conn.close();
        }
        catch (     ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e)
        {
        JOptionPane.showMessageDialog(null, "Eror: "+e,"Gagal",JOptionPane.WARNING_MESSAGE);
        //System.err.println("Exception: "+e.getMessage());
        }
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // Mencari data berdasarkan Data Rekam Medis   
        String no_rm = InputRm.getText();
        try
        {
        Class.forName("com.mysql.jdbc.Driver").newInstance();
        com.mysql.jdbc.Connection conn = (com.mysql.jdbc.Connection) DriverManager.getConnection(
        "jdbc:mysql://localhost:3306/klinik_db", "root", "");
        com.mysql.jdbc.Statement statement = (com.mysql.jdbc.Statement) conn.createStatement();
        String sql="SELECT * FROM pasien WHERE no_rm like '"+no_rm+"'";
         ResultSet view = statement.executeQuery(sql);
        if (view.next())
        {
        nyala(true);
        btnSet(false);
        InputNama.setText(view.getString(2));
        InputUsia.setText(view.getString(3));
        ComboJenisKel.setSelectedItem(view.getString(4));
        ComboStats.setSelectedItem(view.getString(5));
        InputPekerjaan.setText(view.getString(6));
        InputAlamat.setText(view.getString(7));
        InputTelepon.setText(view.getString(8));
        JOptionPane.showMessageDialog(null, "Data berhasil ditemukan","Informasi",JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
        JOptionPane.showMessageDialog(null, "Ops! Data tidak ditemukan.! ","Informasi",JOptionPane.ERROR_MESSAGE);
        }
        statement.close();
        conn.close();
        }
        catch ( ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e)
        {
        JOptionPane.showMessageDialog(null, "Eror:"+e,"Gagal",JOptionPane.WARNING_MESSAGE);
        //System.err.println("Exception: "+e.getMessage());
        }     
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // Menghapus data berdasarkan Data Rekam Medis        
        String no_rm = InputRm.getText();
        try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection conn =  (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/klinik_db", "root", "");
            Statement state =  (Statement) conn.createStatement();
            String sql = "DELETE FROM pasien WHERE no_rm LIKE '"+no_rm+"'";
            state.executeUpdate(sql);
            state.close();
            InputRm.setText("");
            InputNama.setText("");
            InputUsia.setText("");
            ComboJenisKel.setSelectedItem("== PILIH JENIS KELAMIN ==");
            ComboStats.setSelectedItem("== PILIH STATUS ==");
            InputPekerjaan.setText("");
            InputAlamat.setText("");
            InputTelepon.setText("");
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus..","Informasi",JOptionPane.INFORMATION_MESSAGE);
            conn.close();
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e) 
        {
            JOptionPane.showMessageDialog(null, "Eror:"+e,"Gagal",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // Method untuk Edit Data        
        String no_rm = InputRm.getText();
        String nama = InputNama.getText();
        String usia = InputUsia.getText();
        String jenis_kelamin = (String) ComboJenisKel.getSelectedItem();
        String status = (String) ComboStats.getSelectedItem();
        String pekerjaan = InputPekerjaan.getText();
        String alamat = InputAlamat.getText();
        String no_telp = InputTelepon.getText();
        try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection conn =  (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/klinik_db", "root", "");
            Statement state =  (Statement) conn.createStatement();
            String sql ="UPDATE pasien SET NAMA='"+nama+"',USIA='"+usia+"',JENIS_KELAMIN='"+jenis_kelamin+"',STATUS='"+status+"',PEKERJAAN='"+pekerjaan+"'"
                    + ",ALAMAT='"+alamat+"',NO_TELP='"+no_telp+"' WHERE no_rm LIKE'"+no_rm+"'";
            state.executeUpdate(sql);
            state.close();
            JOptionPane.showMessageDialog(null, "Data berhasil diubah..","Informasi",JOptionPane.INFORMATION_MESSAGE);
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e) 
        {
            JOptionPane.showMessageDialog(null, "Eror:"+e,"Gagal",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        new MenuUtama().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataPasien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlamatLabel;
    private javax.swing.JComboBox<String> ComboJenisKel;
    private javax.swing.JComboBox<String> ComboStats;
    private javax.swing.JTextField InputAlamat;
    private javax.swing.JTextField InputNama;
    private javax.swing.JTextField InputPekerjaan;
    private javax.swing.JTextField InputRm;
    private javax.swing.JTextField InputTelepon;
    private javax.swing.JTextField InputUsia;
    private javax.swing.JLabel NamaLabel;
    private javax.swing.JLabel PekerjaanLabel;
    private javax.swing.JLabel RmLabel;
    private javax.swing.JLabel StatusLabel;
    private javax.swing.JLabel TeleponLabel;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
    
    private void nyala (boolean x){
        InputNama.setEditable(x);
        InputUsia.setEditable(x);
        ComboJenisKel.setEditable(x);
        ComboStats.setEditable(x);
        InputPekerjaan.setEditable(x);
        InputAlamat.setEditable(x);
        InputTelepon.setEditable(x);
        InputRm.requestFocus();
    }
    
    private void btnSet (boolean t){
        btnTambah.setEnabled(t);
        btnBatal.setEnabled(!t);
        btnEdit.setEnabled(!t);
        btnHapus.setEnabled(!t);
//        btnKeluar.setEnabled(!t);
        btnSimpan.setEnabled(!t);
    }
}
