/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package klinikbersalinjavaapp;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Locale;
import java.sql.Connection;
import java.sql.Statement;
import javax.swing.Timer;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;


/**
 *
 * @author Farkhanz
 */
public class MenuUtama extends javax.swing.JFrame {
    // Code function atur tanggal    
    java.util.Date saatini = new java.util.Date();
    private SimpleDateFormat simpdafo = new SimpleDateFormat("dd MMMMMMMMM yyyy", Locale.getDefault());
    private String tanggal = simpdafo.format(saatini);
    private Connection conn;
    private Statement state;
    
    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
        setLocationRelativeTo(this);
        TglSaatIni.setText(tanggal);
        setJam();
    }
    
        // Code function atur waktu   
        public final void setJam(){
        ActionListener taskPerformer = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String jam = "", menit = "", detik = "";
                
                java.util.Date Waktu = new java.util.Date();
                int set_jam = Waktu.getHours();
                int set_menit = Waktu.getMinutes();
                int set_detik = Waktu.getSeconds();
                
                if(set_jam <= 9) jam= "0";
                if(set_menit <= 9) menit= "0";
                if(set_detik <= 9) detik= "0";
                
                String hours = jam + Integer.toString(set_jam);
                String minutes = menit + Integer.toString(set_menit);
                String seconds = detik + Integer.toString(set_detik);
                
                wkt1.setText(hours+":"+minutes+":"+seconds);
            }
        };
        new Timer(1000, taskPerformer).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu5 = new javax.swing.JMenu();
        TglSaatIni = new javax.swing.JLabel();
        BackgrounLabel = new javax.swing.JLabel();
        TanggaLabel2 = new javax.swing.JLabel();
        WaktuLabel2 = new javax.swing.JLabel();
        wkt1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MasterFile = new javax.swing.JMenu();
        DataPasien = new javax.swing.JMenuItem();
        DataPetugas = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        Pendaftaran = new javax.swing.JMenu();
        DaftarPemeriksaan = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        StokObat = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        Keluar = new javax.swing.JMenuItem();

        jMenu5.setText("jMenu5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        TglSaatIni.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        TglSaatIni.setText("Tanggal :");

        BackgrounLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/klinikbersalinjavaapp/Rumah_Bersalin2.jpg"))); // NOI18N

        TanggaLabel2.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        TanggaLabel2.setText("Tanggal :");

        WaktuLabel2.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        WaktuLabel2.setText("Waktu :");

        wkt1.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        wkt1.setText("Waktu :");

        MasterFile.setText("Master File");

        DataPasien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        DataPasien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/klinikbersalinjavaapp/People.png"))); // NOI18N
        DataPasien.setText("Data Pasien");
        DataPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataPasienActionPerformed(evt);
            }
        });
        MasterFile.add(DataPasien);

        DataPetugas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        DataPetugas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/klinikbersalinjavaapp/People.png"))); // NOI18N
        DataPetugas.setText("Data Petugas");
        DataPetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataPetugasActionPerformed(evt);
            }
        });
        MasterFile.add(DataPetugas);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/klinikbersalinjavaapp/Retort.png"))); // NOI18N
        jMenuItem1.setText("Data Obat");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MasterFile.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/klinikbersalinjavaapp/Green pin.png"))); // NOI18N
        jMenuItem2.setText("Data Tindakan");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        MasterFile.add(jMenuItem2);

        jMenuBar1.add(MasterFile);

        Pendaftaran.setText("Pendaftaran");

        DaftarPemeriksaan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        DaftarPemeriksaan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/klinikbersalinjavaapp/Bookmark.png"))); // NOI18N
        DaftarPemeriksaan.setText("Daftar Pemeriksaan");
        DaftarPemeriksaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DaftarPemeriksaanActionPerformed(evt);
            }
        });
        Pendaftaran.add(DaftarPemeriksaan);

        jMenuBar1.add(Pendaftaran);

        jMenu1.setText("Stock Obat");

        StokObat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        StokObat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/klinikbersalinjavaapp/Find.png"))); // NOI18N
        StokObat.setText("Stock Obat");
        StokObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StokObatActionPerformed(evt);
            }
        });
        jMenu1.add(StokObat);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Tindakan Medis");

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/klinikbersalinjavaapp/Green pin.png"))); // NOI18N
        jMenuItem4.setText("Tindakan Pemeriksaan");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Laporan");

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/klinikbersalinjavaapp/Print.png"))); // NOI18N
        jMenuItem5.setText("Cetak Pembayaran");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/klinikbersalinjavaapp/Print.png"))); // NOI18N
        jMenuItem6.setText("Cetak Tindakan");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);
        jMenu3.add(jSeparator1);

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/klinikbersalinjavaapp/Report.png"))); // NOI18N
        jMenuItem7.setText("Laporan Pembayaran");
        jMenu3.add(jMenuItem7);

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/klinikbersalinjavaapp/Report.png"))); // NOI18N
        jMenuItem8.setText("Laporan Tindakan");
        jMenu3.add(jMenuItem8);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Tentang");
        jMenuBar1.add(jMenu4);

        jMenu6.setText("Keluar");

        Keluar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        Keluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/klinikbersalinjavaapp/Cancel.png"))); // NOI18N
        Keluar.setText("Keluar");
        Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarActionPerformed(evt);
            }
        });
        jMenu6.add(Keluar);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BackgrounLabel)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(TanggaLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TglSaatIni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(WaktuLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(wkt1)
                .addGap(76, 76, 76))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BackgrounLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wkt1)
                    .addComponent(TglSaatIni)
                    .addComponent(WaktuLabel2)
                    .addComponent(TanggaLabel2))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DataPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataPasienActionPerformed
        // TODO add your handling code here:
        new DataPasien().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_DataPasienActionPerformed

    private void KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarActionPerformed
        int confirm;
        confirm=JOptionPane.showConfirmDialog(null, "Anda Akan Keluar Aplikasi .?", "Informasi", JOptionPane. YES_NO_OPTION);
        if (confirm==JOptionPane.YES_OPTION) {
            System.exit(0);
        }else{
        return;
        }
    }//GEN-LAST:event_KeluarActionPerformed

    private void DataPetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataPetugasActionPerformed
        new Petugas().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_DataPetugasActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new DataTindakan().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new DataObat().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void DaftarPemeriksaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DaftarPemeriksaanActionPerformed
        new DaftarPemeriksaan().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_DaftarPemeriksaanActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        new FormCetakTindakanPeriksa().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void StokObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StokObatActionPerformed
        new StokObat().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_StokObatActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
       new TindakanPemeriksaan().setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        new FormCetakBayar().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgrounLabel;
    private javax.swing.JMenuItem DaftarPemeriksaan;
    private javax.swing.JMenuItem DataPasien;
    private javax.swing.JMenuItem DataPetugas;
    private javax.swing.JMenuItem Keluar;
    private javax.swing.JMenu MasterFile;
    private javax.swing.JMenu Pendaftaran;
    private javax.swing.JMenuItem StokObat;
    private javax.swing.JLabel TanggaLabel2;
    private javax.swing.JLabel TglSaatIni;
    private javax.swing.JLabel WaktuLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel wkt1;
    // End of variables declaration//GEN-END:variables
}
