/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package klinikbersalinjavaapp;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.awt.HeadlessException;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Farkhanz
 */
public class Petugas extends javax.swing.JFrame {

    /**
     * Creates new form petugas
     */
    public Petugas() {
        initComponents();
        setLocationRelativeTo(this);
        nyala(false);
        btnSet(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        PetugasLabel = new javax.swing.JLabel();
        InputidPetugas = new javax.swing.JTextField();
        CariPetugas = new javax.swing.JButton();
        InputNamaPetugas = new javax.swing.JTextField();
        InputAlamatPetugas = new javax.swing.JTextField();
        InputTelPetugas = new javax.swing.JTextField();
        PetugasLabel1 = new javax.swing.JLabel();
        PetugasLabel2 = new javax.swing.JLabel();
        PetugasLabel3 = new javax.swing.JLabel();
        TambahPetugas = new javax.swing.JButton();
        SimpanPetugas = new javax.swing.JButton();
        EditPetugas = new javax.swing.JButton();
        KeluarPetugas = new javax.swing.JButton();
        HapusPetugas = new javax.swing.JButton();
        BatalPetugas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DATA PETUGAS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(102, 102, 102))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        PetugasLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        PetugasLabel.setText("ID Petugas");

        InputidPetugas.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        CariPetugas.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        CariPetugas.setText("CARI");
        CariPetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CariPetugasActionPerformed(evt);
            }
        });

        InputNamaPetugas.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        InputAlamatPetugas.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        InputTelPetugas.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        PetugasLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        PetugasLabel1.setText("Nama");

        PetugasLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        PetugasLabel2.setText("Alamat");

        PetugasLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        PetugasLabel3.setText("No.Telp");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PetugasLabel)
                    .addComponent(PetugasLabel1)
                    .addComponent(PetugasLabel2)
                    .addComponent(PetugasLabel3))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(InputidPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CariPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(InputAlamatPetugas)
                    .addComponent(InputTelPetugas)
                    .addComponent(InputNamaPetugas))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PetugasLabel)
                    .addComponent(InputidPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CariPetugas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputNamaPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PetugasLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputAlamatPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PetugasLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputTelPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PetugasLabel3))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        TambahPetugas.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        TambahPetugas.setText("Tambah");
        TambahPetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahPetugasActionPerformed(evt);
            }
        });

        SimpanPetugas.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        SimpanPetugas.setText("Simpan");
        SimpanPetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanPetugasActionPerformed(evt);
            }
        });

        EditPetugas.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        EditPetugas.setText("Edit");
        EditPetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditPetugasActionPerformed(evt);
            }
        });

        KeluarPetugas.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        KeluarPetugas.setText("Keluar");
        KeluarPetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarPetugasActionPerformed(evt);
            }
        });

        HapusPetugas.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        HapusPetugas.setText("Hapus");
        HapusPetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusPetugasActionPerformed(evt);
            }
        });

        BatalPetugas.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BatalPetugas.setText("Batal");
        BatalPetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BatalPetugasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(HapusPetugas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TambahPetugas, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BatalPetugas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SimpanPetugas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EditPetugas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(KeluarPetugas, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TambahPetugas)
                    .addComponent(SimpanPetugas)
                    .addComponent(EditPetugas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HapusPetugas)
                    .addComponent(BatalPetugas)
                    .addComponent(KeluarPetugas))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SimpanPetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanPetugasActionPerformed
        // Simpan Data Petugas
        String id_petugas = InputidPetugas.getText();
        String nama = InputNamaPetugas.getText();
        String alamat = InputAlamatPetugas.getText();
        String no_telp = InputTelPetugas.getText();
        
        {
        try
        {
        Class.forName("com.mysql.jdbc.Driver").newInstance();
        Connection conn = (Connection) DriverManager.getConnection(
        "jdbc:mysql://localhost:3306/klinik_db", "root", "");
        Statement state = (Statement) conn.createStatement();
        String sql="insert into petugas values('"+id_petugas+"','"+nama+"','"+alamat+"','"+no_telp+"')";
        int executeUpdate = state.executeUpdate(sql);
        state.close();
        JOptionPane.showMessageDialog(null, "Data petugas berhasil disimpan..","Insert Data",JOptionPane.INFORMATION_MESSAGE);
        nyala(true);
        InputidPetugas.setText("");
        InputNamaPetugas.setText("");
        InputAlamatPetugas.setText("");
        InputTelPetugas.setText("");
        //txtnpm.setFocusable(rootPaneCheckingEnabled);
        conn.close();
        }
        catch (     ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e)
        {
        JOptionPane.showMessageDialog(null, "Eror: "+e,"Gagal",JOptionPane.WARNING_MESSAGE);
        //System.err.println("Exception: "+e.getMessage());
        }
        }
    }//GEN-LAST:event_SimpanPetugasActionPerformed

    private void TambahPetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahPetugasActionPerformed
        nyala(true);
        btnSet(false);
    }//GEN-LAST:event_TambahPetugasActionPerformed

    private void BatalPetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BatalPetugasActionPerformed
        InputidPetugas.setText("");
        InputNamaPetugas.setText("");
        InputAlamatPetugas.setText("");
        InputTelPetugas.setText("");
    }//GEN-LAST:event_BatalPetugasActionPerformed

    private void HapusPetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusPetugasActionPerformed
        String nip = InputidPetugas.getText();
        try {
        Class.forName("com.mysql.jdbc.Driver").newInstance();
        Connection conn = (Connection) DriverManager.getConnection(
        "jdbc:mysql://localhost:3306/klinik_db", "root", "");
        Statement state = (Statement) conn.createStatement();
        String sql="DELETE FROM petugas WHERE nip LIKE '"+nip+"'";
        state.executeUpdate(sql);
        state.close();
        InputidPetugas.setText("");
        InputNamaPetugas.setText("");
        InputAlamatPetugas.setText("");
        InputTelPetugas.setText("");
        JOptionPane.showMessageDialog(null, "Data petugas berhasil dihapus..","Insert Data",JOptionPane.INFORMATION_MESSAGE);
        conn.close();
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e) { JOptionPane.showMessageDialog(null, "Eror: "+e,"Gagal",JOptionPane.WARNING_MESSAGE);
        //System.err.println("Exception: "+e.getMessage());
        }
    }//GEN-LAST:event_HapusPetugasActionPerformed

    private void EditPetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditPetugasActionPerformed
        String nip = InputidPetugas.getText();
        String nama = InputNamaPetugas.getText();
        String alamat = InputAlamatPetugas.getText();
        String no_telp = InputTelPetugas.getText();
        
        try {
        Class.forName("com.mysql.jdbc.Driver").newInstance();
        Connection koneksi = (Connection) DriverManager.getConnection(
        "jdbc:mysql://localhost:3306/klinik_db", "root", "");
        Statement statement = (Statement) koneksi.createStatement();
        String sql="UPDATE petugas SET NAMA='"+nama+"',ALAMAT='"+alamat+"',NO_TELP='"+no_telp+"' WHERE nip LIKE '"+nip+"'";
        statement.executeUpdate(sql);
        statement.close();
        JOptionPane.showMessageDialog(null, "Data berhasil diubah..","Insert Data",JOptionPane.INFORMATION_MESSAGE);
        koneksi.close();
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e) {
        JOptionPane.showMessageDialog(null, "Eror: "+e,"Gagal",JOptionPane.WARNING_MESSAGE);
        //System.err.println("Exception: "+e.getMessage());
        }
    }//GEN-LAST:event_EditPetugasActionPerformed

    private void KeluarPetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarPetugasActionPerformed
        new MenuUtama().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_KeluarPetugasActionPerformed

    private void CariPetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CariPetugasActionPerformed
        String nip = InputidPetugas.getText();
        try
        {
        Class.forName("com.mysql.jdbc.Driver").newInstance();
        Connection koneksi = (Connection) DriverManager.getConnection(
        "jdbc:mysql://localhost:3306/klinik_db", "root", "");
        Statement statement = (Statement) koneksi.createStatement();
        String sql="SELECT * FROM petugas WHERE nip like '"+nip+"'";
         ResultSet view = statement.executeQuery(sql);
        if (view.next())
        {
        nyala(true);
        btnSet(false);
        InputNamaPetugas.setText(view.getString(2));
        InputAlamatPetugas.setText(view.getString(3));
        InputTelPetugas.setText(view.getString(4));
        JOptionPane.showMessageDialog(null, "Data ditemukan","Insert Data",JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
        JOptionPane.showMessageDialog(null, "Data tidak ditemukan ","Insert Data",JOptionPane.INFORMATION_MESSAGE);
        }
        statement.close();
        koneksi.close();
        }
        catch ( ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e)
        {
        JOptionPane.showMessageDialog(null, "Eror:"+e,"Gagal",JOptionPane.WARNING_MESSAGE);
        //System.err.println("Exception: "+e.getMessage());
        }
    }//GEN-LAST:event_CariPetugasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Petugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Petugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Petugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Petugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Petugas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BatalPetugas;
    private javax.swing.JButton CariPetugas;
    private javax.swing.JButton EditPetugas;
    private javax.swing.JButton HapusPetugas;
    private javax.swing.JTextField InputAlamatPetugas;
    private javax.swing.JTextField InputNamaPetugas;
    private javax.swing.JTextField InputTelPetugas;
    private javax.swing.JTextField InputidPetugas;
    private javax.swing.JButton KeluarPetugas;
    private javax.swing.JLabel PetugasLabel;
    private javax.swing.JLabel PetugasLabel1;
    private javax.swing.JLabel PetugasLabel2;
    private javax.swing.JLabel PetugasLabel3;
    private javax.swing.JButton SimpanPetugas;
    private javax.swing.JButton TambahPetugas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
    
    private void nyala (boolean x){
        InputNamaPetugas.setEditable(x);
        InputAlamatPetugas.setEditable(x);
        InputTelPetugas.setEditable(x);
        InputidPetugas.requestFocus();
    }
    
    private void btnSet (boolean y){
        TambahPetugas.setEnabled(y);
        SimpanPetugas.setEnabled(!y);
        EditPetugas.setEnabled(!y);
        HapusPetugas.setEnabled(!y);
        BatalPetugas.setEnabled(!y);
//        KeluarPetugas.setEnabled(!y);
    }
}
