/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package klinikbersalinjavaapp;

import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Farkhanz
 */
public class TindakanPemeriksaan extends javax.swing.JFrame {

    // Code function atur tanggal    
    java.util.Date saatini = new java.util.Date();
    private SimpleDateFormat simpdafo = new SimpleDateFormat("dd MMMMMMMMM yyyy", Locale.getDefault());
    private String tanggal = simpdafo.format(saatini);
    private Connection conn;
    private Statement state;
    /**
     * Creates new form TindakanPemeriksaan
     */
    public TindakanPemeriksaan() {
        initComponents();
        setLocationRelativeTo(this);
        setJam();
        TglSaatIni.setText(tanggal);
    }  
        
        // Code function atur waktu   
        public final void setJam(){
        ActionListener taskPerformer = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String jam = "", menit = "", detik = "";
                
                java.util.Date Waktu = new java.util.Date();
                int set_jam = Waktu.getHours();
                int set_menit = Waktu.getMinutes();
                int set_detik = Waktu.getSeconds();
                
                if(set_jam <= 9) jam= "0";
                if(set_menit <= 9) menit= "0";
                if(set_detik <= 9) detik= "0";
                
                String hours = jam + Integer.toString(set_jam);
                String minutes = menit + Integer.toString(set_menit);
                String seconds = detik + Integer.toString(set_detik);
                
                wkt1.setText(hours+":"+minutes+":"+seconds);
            }
        };
        new Timer(1000, taskPerformer).start();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        InputNoDaftar = new javax.swing.JTextField();
        InputRekamMedis = new javax.swing.JTextField();
        InputNamaPasien = new javax.swing.JTextField();
        InputPemeriksaan = new javax.swing.JTextField();
        InputNamaTindakan = new javax.swing.JTextField();
        InputHargaTindakan = new javax.swing.JTextField();
        CariDaftar = new javax.swing.JButton();
        ComboTindakan = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        InputHargaRuang = new javax.swing.JTextField();
        ComboRuang = new javax.swing.JComboBox();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        InputKeadaanBayi = new javax.swing.JTextField();
        InputJenisKelaminBayi = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        InputNoPeriksa = new javax.swing.JTextField();
        ComboNoPetugas = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        InputNamaPemeriksa = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        InputDiagnosa = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        ComboKodeObat = new javax.swing.JComboBox();
        InputNamaObat = new javax.swing.JTextField();
        InputJumlahPemakaian = new javax.swing.JTextField();
        InputSatuan = new javax.swing.JTextField();
        InputHarga = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        InputNoResep = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        InputRincianObat = new javax.swing.JTextField();
        SimpanResep = new javax.swing.JButton();
        InputStockAwal = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        InputStockAkhir = new javax.swing.JTextField();
        InputJenis = new javax.swing.JTextField();
        InputStockMin = new javax.swing.JTextField();
        InputSupplier = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        btupdateobat = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        InputJumlah = new javax.swing.JTextField();
        InputTotalBiaya = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        SimpanData = new javax.swing.JButton();
        BatalPeriksa = new javax.swing.JButton();
        Keluar = new javax.swing.JButton();
        TanggaLabel2 = new javax.swing.JLabel();
        TglSaatIni = new javax.swing.JLabel();
        WaktuLabel2 = new javax.swing.JLabel();
        wkt1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tindakan Pemeriksaan");
        jDesktopPane1.add(jLabel1);
        jLabel1.setBounds(230, 0, 330, 40);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel4.setText("No Daftar");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel7.setText("No Rekam Medis");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel8.setText("Nama Pasien");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel10.setText("Pemeriksaan");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel11.setText("Kode Tindakan");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel5.setText("Nama Tindakan");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel6.setText("Harga Tindakan");

        InputNoDaftar.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        InputNoDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputNoDaftarActionPerformed(evt);
            }
        });
        InputNoDaftar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                InputNoDaftarKeyReleased(evt);
            }
        });

        InputRekamMedis.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        InputNamaPasien.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        InputPemeriksaan.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        InputNamaTindakan.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        InputHargaTindakan.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        CariDaftar.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        CariDaftar.setText("Cari");
        CariDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CariDaftarActionPerformed(evt);
            }
        });

        ComboTindakan.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        ComboTindakan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "::::::: PILIH KODE ::::::::", "T-0001", "T-0002", "T-0003", "T-0004", "T-0005", "T-0006", "T-0007", "T-0008", "T-0009", "T-0010" }));
        ComboTindakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboTindakanActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel24.setText("Ruang Bersalin");

        jLabel25.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel25.setText("Harga Ruang");

        InputHargaRuang.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        ComboRuang.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        ComboRuang.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "= PILIH RUANGAN =", "RUANG MARWAH", "RUANG MUZDALIFAH", "RUANG MULTAZAM", "RUANG SHAFA" }));
        ComboRuang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboRuangActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel26.setText("Keadaan Bayi");

        jLabel27.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel27.setText("Jenis Kelamin bayi");

        InputKeadaanBayi.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        InputJenisKelaminBayi.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jLabel32.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel32.setText("No Periksa");

        InputNoPeriksa.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        InputNoPeriksa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputNoPeriksaActionPerformed(evt);
            }
        });

        ComboNoPetugas.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        ComboNoPetugas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { ":::::::: PILIH KODE ::::::::", "P-0001", "P-0002", "P-0003", "P-0004", "P-0005", "P-0006", "P-0007", "P-0008", "P-0009", "P-0010", " ", " " }));
        ComboNoPetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboNoPetugasActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel13.setText("No Petugas");

        InputNamaPemeriksa.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel14.setText("Nama Pemeriksa");

        jLabel21.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel21.setText("Diagnosa");

        InputDiagnosa.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27)
                    .addComponent(jLabel32)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel21))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InputDiagnosa, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputNamaPemeriksa, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputNoPeriksa, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(ComboNoPetugas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(InputNamaPasien)
                            .addComponent(InputPemeriksaan)
                            .addComponent(InputNamaTindakan)
                            .addComponent(InputHargaTindakan)
                            .addComponent(ComboTindakan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ComboRuang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(InputHargaRuang)
                            .addComponent(InputKeadaanBayi)
                            .addComponent(InputJenisKelaminBayi)
                            .addComponent(InputRekamMedis)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(InputNoDaftar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CariDaftar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(InputNoPeriksa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputNoDaftar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CariDaftar)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputRekamMedis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputNamaPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputPemeriksaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(ComboTindakan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputNamaTindakan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputHargaTindakan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(ComboRuang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(InputHargaRuang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputKeadaanBayi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputJenisKelaminBayi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboNoPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputNamaPemeriksa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(InputDiagnosa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel15.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel15.setText("Kode Obat");

        jLabel16.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel16.setText("Nama Obat");

        jLabel18.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel18.setText("Jumlah Pemakaian");

        jLabel19.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel19.setText("Satuan");

        jLabel20.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel20.setText("Harga");

        ComboKodeObat.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        ComboKodeObat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { ":::::::: PILIH KODE ::::::::", "O-0001", "O-0002", "O-0003", "O-0004", "O-0005", "O-0006", "O-0007", "O-0008", "O-0009", "O-0010" }));
        ComboKodeObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboKodeObatActionPerformed(evt);
            }
        });

        InputNamaObat.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        InputNamaObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputNamaObatActionPerformed(evt);
            }
        });

        InputJumlahPemakaian.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        InputSatuan.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        InputHarga.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jLabel22.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel22.setText("No Resep");

        InputNoResep.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        InputNoResep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputNoResepActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel23.setText("Rincian Obat");

        InputRincianObat.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        SimpanResep.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        SimpanResep.setText("Simpan Resep");
        SimpanResep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanResepActionPerformed(evt);
            }
        });

        InputStockAwal.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jLabel28.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel28.setText("Stock awal");

        jLabel29.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel29.setText("Stock akhir");

        InputStockAkhir.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        InputStockAkhir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputStockAkhirActionPerformed(evt);
            }
        });

        InputJenis.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        InputStockMin.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        InputSupplier.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel12.setText("Jenis");

        jLabel30.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel30.setText("Stock min");

        jLabel31.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel31.setText("Supplier");

        btupdateobat.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btupdateobat.setText("Update");
        btupdateobat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btupdateobatActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel9.setText("Jumlah");

        jLabel17.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel17.setText("Total_biaya");

        InputJumlah.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        InputJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputJumlahActionPerformed(evt);
            }
        });

        InputTotalBiaya.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        InputTotalBiaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputTotalBiayaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29)
                    .addComponent(jLabel12)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31)
                    .addComponent(jLabel9)
                    .addComponent(jLabel17))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(SimpanResep)
                        .addComponent(ComboKodeObat, 0, 197, Short.MAX_VALUE)
                        .addComponent(InputNamaObat)
                        .addComponent(InputJumlahPemakaian)
                        .addComponent(InputSatuan)
                        .addComponent(InputHarga)
                        .addComponent(InputNoResep)
                        .addComponent(InputRincianObat)
                        .addComponent(InputStockAwal)
                        .addComponent(InputStockAkhir)
                        .addComponent(InputJenis)
                        .addComponent(InputStockMin))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(InputTotalBiaya, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(InputJumlah, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(InputSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btupdateobat))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputNoResep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputRincianObat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SimpanResep)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboKodeObat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputNamaObat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputJumlahPemakaian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputStockAwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputStockAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputStockMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(btupdateobat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(InputJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(InputTotalBiaya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel3.setBackground(new java.awt.Color(255, 204, 102));

        SimpanData.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        SimpanData.setText("Simpan");
        SimpanData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanDataActionPerformed(evt);
            }
        });

        BatalPeriksa.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        BatalPeriksa.setText("Batal");
        BatalPeriksa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BatalPeriksaActionPerformed(evt);
            }
        });

        Keluar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Keluar.setText("Keluar");
        Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(SimpanData, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109)
                .addComponent(BatalPeriksa, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BatalPeriksa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SimpanData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        TanggaLabel2.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        TanggaLabel2.setText("Tanggal :");

        TglSaatIni.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        TglSaatIni.setText("Tanggal :");

        WaktuLabel2.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        WaktuLabel2.setText("Waktu :");

        wkt1.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        wkt1.setText("Waktu :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TanggaLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TglSaatIni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(WaktuLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(wkt1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wkt1)
                    .addComponent(TglSaatIni)
                    .addComponent(WaktuLabel2)
                    .addComponent(TanggaLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InputNoDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputNoDaftarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputNoDaftarActionPerformed

    private void InputNoDaftarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InputNoDaftarKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_InputNoDaftarKeyReleased

    private void CariDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CariDaftarActionPerformed
        // TODO add your handling code here:
        String no_daftar = InputNoDaftar.getText();
        try
        {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection conn = (Connection) DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/klinik_db", "root", "");
            Statement state = (Statement) conn.createStatement();
            String sql="SELECT * FROM daftar WHERE no_daftar like '"+no_daftar+"'";
            ResultSet view = state.executeQuery(sql);
            if (view.next())
            {
                InputRekamMedis.setText(view.getString(4));
                InputNamaPasien.setText(view.getString(5));
                InputPemeriksaan.setText(view.getString(6));
                JOptionPane.showMessageDialog(null, "Data ditemukan","Informasi",JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Data tidak ditemukan ","Informasi",JOptionPane.INFORMATION_MESSAGE);
            }
            state.close();
            conn.close();
        }
        catch ( ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e)
        {
            JOptionPane.showMessageDialog(null, "Eror:"+e,"Gagal",JOptionPane.WARNING_MESSAGE);
            //System.err.println("Exception: "+e.getMessage());
        }
    }//GEN-LAST:event_CariDaftarActionPerformed

    private void ComboTindakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboTindakanActionPerformed
        data_tindakan();
        if(ComboTindakan.getSelectedItem().equals("T-0008")){
            nyala(true);
        }else if(ComboTindakan.getSelectedItem().equals("T-0007")){nyala(true);}
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboTindakanActionPerformed

    private void ComboRuangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboRuangActionPerformed
        // TODO add your handling code here:
        if(ComboRuang.getSelectedItem().equals("RUANG MARWAH")){
            InputHargaRuang.setText("100000");
        }
        else if(ComboRuang.getSelectedItem().equals("RUANG MUZDALIFAH")){
            InputHargaRuang.setText("90000");
        }
        else if(ComboRuang.getSelectedItem().equals("RUANG MULTAZAM")){
            InputHargaRuang.setText("30000");
        }
        else{InputHargaRuang.setText("75000");
        }
    }//GEN-LAST:event_ComboRuangActionPerformed

    private void InputNoPeriksaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputNoPeriksaActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection koneksi = (Connection) DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/rumahbersalin", "root", "");
            Statement statement = (Statement) koneksi.createStatement();
            String sql = "SELECT * FROM periksa order by no_per";
            ResultSet rs = statement.executeQuery(sql);
            if (rs.first() == false) {
                InputNoPeriksa.setText("000001");
            } else {
                rs.last();
                int no = rs.getInt(1) + 1;
                String cno=String.valueOf(no);
                int pjg_cno=cno.length();
                for (int i=0;i<3-pjg_cno;i++)
                {
                    cno="0"+cno;
                }
                InputNoPeriksa.setText("000"+cno);

            }
            statement.close();
            koneksi.close();
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Eror:" + e, "Gagal", JOptionPane.WARNING_MESSAGE);
            //System.err.println("Exception: "+e.getMessage());
        }
    }//GEN-LAST:event_InputNoPeriksaActionPerformed

    private void ComboNoPetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboNoPetugasActionPerformed
        data_petugas();

        // TODO add your handling code here:
    }//GEN-LAST:event_ComboNoPetugasActionPerformed

    private void ComboKodeObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboKodeObatActionPerformed
        // TODO add your handling code here:
        String kode = (String) ComboKodeObat.getSelectedItem();
        try
        {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection koneksi = (Connection) DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/rumahbersalin", "root", "");
            Statement statement = (Statement) koneksi.createStatement();
            String sql="SELECT * FROM obat WHERE kode like '"+kode+"'";
            ResultSet rs = statement.executeQuery(sql);
            if (rs.next())
            {
                InputJumlahPemakaian.requestFocus();
                InputNamaObat.setText(rs.getString(2));
                InputJenis.setText(rs.getString(3));
                InputSatuan.setText(rs.getString(4));
                InputHarga.setText(rs.getString(5));
                InputStockAwal.setText(rs.getString(6));
                InputStockMin.setText(rs.getString(7));
                InputSupplier.setText(rs.getString(8));
            } else {
                JOptionPane.showMessageDialog(null, "Data Tidak Ada");
            } } catch (Exception e){ }
    }//GEN-LAST:event_ComboKodeObatActionPerformed

    private void InputNamaObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputNamaObatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputNamaObatActionPerformed

    private void InputNoResepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputNoResepActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection koneksi = (Connection) DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/rumahbersalin", "root", "");
            Statement statement = (Statement) koneksi.createStatement();
            String sql = "SELECT * FROM resep order by no_resep";
            ResultSet rs = statement.executeQuery(sql);
            if (rs.first() == false) {
                InputNoResep.setText("000001");
            } else {
                rs.last();
                int no = rs.getInt(1) + 1;
                String cno=String.valueOf(no);
                int pjg_cno=cno.length();
                for (int i=0;i<3-pjg_cno;i++)
                {
                    cno="0"+cno;
                }
                InputNoResep.setText("000"+cno);

            }
            statement.close();
            koneksi.close();
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Eror:" + e, "Gagal", JOptionPane.WARNING_MESSAGE);
            //System.err.println("Exception: "+e.getMessage());
        }
    }//GEN-LAST:event_InputNoResepActionPerformed

    private void SimpanResepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanResepActionPerformed
        // TODO add your handling code here:
        String no_resep = InputNoResep.getText();
        String tgl_resep = TglSaatIni.getText();
        String rincian_obat = InputRincianObat.getText();
        {
            try
            {
                Class.forName("com.mysql.jdbc.Driver").newInstance();
                Connection conn = (Connection) DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/klinik_db", "root", "");
                Statement state = (Statement) conn.createStatement();
                String sql="insert into resep values('"+no_resep+"','"+tgl_resep+"','"+rincian_obat+"')";
                int executeUpdate = state.executeUpdate(sql);
                state.close();
                JOptionPane.showMessageDialog(null, "Data berhasil disimpan.!","Insert Data",JOptionPane.INFORMATION_MESSAGE);
                online(true);
                InputRincianObat.setText("");
                conn.close();
            }
            catch (     ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e)
            {
                JOptionPane.showMessageDialog(null, "Eror: "+e,"Gagal",JOptionPane.WARNING_MESSAGE);
                //System.err.println("Exception: "+e.getMessage());
            }
        }
    }//GEN-LAST:event_SimpanResepActionPerformed

    private void InputStockAkhirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputStockAkhirActionPerformed
        // TODO add your handling code here:
        double xakh,xawl,xjml;
        xawl=Double.parseDouble(InputStockAwal.getText());
        xjml=Double.parseDouble(InputJumlahPemakaian.getText());
        xakh=xawl-xjml;
        String xtotal=Double.toString(xakh);
        InputStockAkhir.setText(xtotal);
    }//GEN-LAST:event_InputStockAkhirActionPerformed

    private void btupdateobatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btupdateobatActionPerformed
        // TODO add your handling code here:
        obat();
    }//GEN-LAST:event_btupdateobatActionPerformed

    private void InputJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputJumlahActionPerformed
        // TODO add your handling code here:
        double xtot,xhrg,xjml;
        xhrg=Double.parseDouble(InputHarga.getText());
        xjml=Double.parseDouble(InputJumlahPemakaian.getText());
        xtot=xjml*xhrg;
        String xtotal=Double.toString(xtot);
        InputJumlah.setText(xtotal);
    }//GEN-LAST:event_InputJumlahActionPerformed

    private void InputTotalBiayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputTotalBiayaActionPerformed
        hitung();        // TODO add your handling code here:
    }//GEN-LAST:event_InputTotalBiayaActionPerformed

    private void SimpanDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanDataActionPerformed
        // TODO add your handling code here:
            String no_per = InputNoPeriksa.getText();
            String no_daftar = InputNoDaftar.getText();
            String tanggal = TglSaatIni.getText();
            String jam = wkt1.getText();
            String no_rm = InputRekamMedis.getText();
            String nama = InputNamaPasien.getText();
            String kd_tin = (String) ComboTindakan.getSelectedItem();
            String harga = InputHargaTindakan.getText();
            String ruang_bersalin = (String) ComboRuang.getSelectedItem();
            String harga_ruang = InputHargaRuang.getText();
            String keadaan_bayi = InputKeadaanBayi.getText();
            String jenkel_bayi = InputJenisKelaminBayi.getText();
            String id_petugas = (String) ComboNoPetugas.getSelectedItem();
            String diagnosa = InputDiagnosa.getText();
            String no_resep = InputNoResep.getText();
            String kode = (String) ComboKodeObat.getSelectedItem();
            String total_biaya = InputTotalBiaya.getText();
            {
            try
            {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            com.mysql.jdbc.Connection koneksi = (com.mysql.jdbc.Connection) DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/klinik_db", "root", "");
            com.mysql.jdbc.Statement statement = (com.mysql.jdbc.Statement) koneksi.createStatement();
            String sql="insert into periksa values('"+no_per+"','"+no_daftar+"','"+tanggal+"','"+jam+"','"+no_rm+"','"+nama+"','"+kd_tin+"','"+ruang_bersalin+"','"+harga_ruang+"','"+keadaan_bayi+"','"+jenkel_bayi+"','"+id_petugas+"','"+diagnosa+"','"+no_resep+"','"+kode+"','"+total_biaya+"')";
            int executeUpdate = statement.executeUpdate(sql);
            statement.close();
            JOptionPane.showMessageDialog(null, "Data berhasil dimasukkan..","Insert Data",JOptionPane.INFORMATION_MESSAGE);
            nyala(true);
            InputNoDaftar.setText("");
                    InputRekamMedis.setText("");
                    InputNamaPasien.setText("");
                    InputPemeriksaan.setText("");
                    ComboTindakan.setSelectedItem(0);
                    InputNamaTindakan.setText("");
                    InputHargaTindakan.setText("");
                    ComboNoPetugas.setSelectedItem(0);
                    InputNamaPemeriksa.setText("");
                    ComboKodeObat.setSelectedItem(0);
                    InputNamaObat.setText("");
                    InputJumlahPemakaian.setText("");
                    InputSatuan.setText("");
                    InputHarga.setText("");
                    InputStockAwal.setText("");
                    InputStockAkhir.setText("");
                    InputNoPeriksa.setText("");
                    InputJenis.setText("");
                    InputStockMin.setText("");
                    InputSupplier.setText("");
                    InputJumlah.setText("");
                    InputTotalBiaya.setText("");
                    new Transaksi().setVisible(true);
                    this.dispose();
            koneksi.close();
            }
            catch (     ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e)
            {
            JOptionPane.showMessageDialog(null, "Eror: "+e,"Gagal",JOptionPane.WARNING_MESSAGE);
            //System.err.println("Exception: "+e.getMessage());
            }
            }
    }//GEN-LAST:event_SimpanDataActionPerformed

    private void BatalPeriksaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BatalPeriksaActionPerformed
        // TODO add your handling code here:
        InputNoDaftar.setText("");
        InputRekamMedis.setText("");
        InputNamaPasien.setText("");
        InputPemeriksaan.setText("");
        ComboTindakan.setSelectedItem(0);
        InputNamaTindakan.setText("");
        InputHargaTindakan.setText("");
        ComboNoPetugas.setSelectedItem(0);
        InputNamaPemeriksa.setText("");
        ComboKodeObat.setSelectedItem(0);
        InputNamaObat.setText("");
        InputJumlahPemakaian.setText("");
        InputSatuan.setText("");
        InputHarga.setText("");
        InputStockAwal.setText("");
        InputStockAkhir.setText("");
        InputNoPeriksa.setText("");
        InputJenis.setText("");
        InputStockMin.setText("");
        InputSupplier.setText("");
        InputJumlah.setText("");
        InputTotalBiaya.setText("");

    }//GEN-LAST:event_BatalPeriksaActionPerformed

    private void KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_KeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TindakanPemeriksaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TindakanPemeriksaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TindakanPemeriksaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TindakanPemeriksaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TindakanPemeriksaan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BatalPeriksa;
    private javax.swing.JButton CariDaftar;
    private javax.swing.JComboBox ComboKodeObat;
    private javax.swing.JComboBox ComboNoPetugas;
    private javax.swing.JComboBox ComboRuang;
    private javax.swing.JComboBox ComboTindakan;
    private javax.swing.JTextField InputDiagnosa;
    private javax.swing.JTextField InputHarga;
    private javax.swing.JTextField InputHargaRuang;
    private javax.swing.JTextField InputHargaTindakan;
    private javax.swing.JTextField InputJenis;
    private javax.swing.JTextField InputJenisKelaminBayi;
    private javax.swing.JTextField InputJumlah;
    private javax.swing.JTextField InputJumlahPemakaian;
    private javax.swing.JTextField InputKeadaanBayi;
    private javax.swing.JTextField InputNamaObat;
    private javax.swing.JTextField InputNamaPasien;
    private javax.swing.JTextField InputNamaPemeriksa;
    private javax.swing.JTextField InputNamaTindakan;
    private javax.swing.JTextField InputNoDaftar;
    private javax.swing.JTextField InputNoPeriksa;
    private javax.swing.JTextField InputNoResep;
    private javax.swing.JTextField InputPemeriksaan;
    private javax.swing.JTextField InputRekamMedis;
    private javax.swing.JTextField InputRincianObat;
    private javax.swing.JTextField InputSatuan;
    private javax.swing.JTextField InputStockAkhir;
    private javax.swing.JTextField InputStockAwal;
    private javax.swing.JTextField InputStockMin;
    private javax.swing.JTextField InputSupplier;
    private javax.swing.JTextField InputTotalBiaya;
    private javax.swing.JButton Keluar;
    private javax.swing.JButton SimpanData;
    private javax.swing.JButton SimpanResep;
    private javax.swing.JLabel TanggaLabel2;
    private javax.swing.JLabel TglSaatIni;
    private javax.swing.JLabel WaktuLabel2;
    private javax.swing.JButton btupdateobat;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel wkt1;
    // End of variables declaration//GEN-END:variables

    private void online (boolean a){
      InputDiagnosa.setEditable(a);
      InputNoResep.setEditable(a);
      InputRincianObat.setEditable(a);
      SimpanResep.setEnabled(a);
    }
    
    private void nyala (boolean x){
      InputRekamMedis.setEditable(x);
      InputNamaPasien.setEditable(x);
      InputNamaTindakan.setEditable(x);
      InputHarga.setEditable(x);
      InputHargaTindakan.setEditable(x);
      InputNamaPemeriksa.setEditable(x);
      InputNamaObat.setEditable(x);
      InputPemeriksaan.setEditable(x);
      InputSatuan.setEditable(x);
      InputHargaRuang.setEditable(x);
      ComboRuang.setEnabled(x);
      InputKeadaanBayi.setEditable(x);
      InputJenisKelaminBayi.setEditable(x);
      InputStockMin.setEditable(x);
      InputSupplier.setEditable(x);
      InputJenis.setEditable(x);
      InputStockAwal.setEditable(x);
    }
    
    private void data_tindakan(){
        String kd_tindakan = (String) ComboTindakan.getSelectedItem();
        try {
           Class.forName("com.mysql.jdbc.Driver").newInstance();
           Connection conn = (Connection) DriverManager.getConnection(
           "jdbc:mysql://localhost:3306/klinik_db", "root", "");
           Statement state = (Statement) conn.createStatement();
           String sql="SELECT * FROM tindakan where kd_tindakan like '"+kd_tindakan+"'";
            ResultSet view = state.executeQuery(sql);
            if (view.next())
           {
           InputNamaTindakan.setText(view.getString(2));
           InputHargaTindakan.setText(view.getString(3));
           } else {
           JOptionPane.showMessageDialog(null, "Data Tidak Ada");
           } } catch (Exception e){ }
    }
    
    private void data_petugas(){
        String nip = (String) ComboNoPetugas.getSelectedItem();
            try
            {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection conn = (Connection) DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/klinik_db", "root", "");
            Statement state = (Statement) conn.createStatement();
            String sql="SELECT * FROM petugas WHERE nip like '"+nip+"'";
             ResultSet view = state.executeQuery(sql);
            if (view.next())
            {
            InputNamaPemeriksa.setText(view.getString(2));
            } else {
            JOptionPane.showMessageDialog(null, "Data Tidak Ada");
            } } catch (Exception e){ }
    }
    
    private void obat(){
        String kode = (String) ComboKodeObat.getSelectedItem();
        String nama_obat = InputNamaObat.getText();
        String jenis = InputJenis.getText();
        String satuan = InputSatuan.getText();
        String harga = InputHarga.getText();
        String stok = InputStockAkhir.getText();
        String stokmin = InputStockMin.getText();
        String suplier = InputSupplier.getText();
        try {
        Class.forName("com.mysql.jdbc.Driver").newInstance();
        com.mysql.jdbc.Connection conn = (com.mysql.jdbc.Connection) DriverManager.getConnection(
        "jdbc:mysql://localhost:3306/klinik_db", "root", "");
        com.mysql.jdbc.Statement state = (com.mysql.jdbc.Statement) conn.createStatement();
        String sql="UPDATE obat SET NAMA_OBAT='"+nama_obat+"',JENIS='"+jenis+"',SATUAN='"+satuan+"',HARGA='"+harga+"',STOK='"+stok+"',STOKMIN='"+stokmin+"',SUPLIER='"+suplier+"' WHERE kode_obat LIKE '"+kode+"'";
        state.executeUpdate(sql);
        state.close();
        JOptionPane.showMessageDialog(null, "Data berhasil diedit..","Insert Data",JOptionPane.INFORMATION_MESSAGE);
        conn.close();
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e) {
        JOptionPane.showMessageDialog(null, "Eror: "+e,"Gagal",JOptionPane.WARNING_MESSAGE);
        //System.err.println("Exception: "+e.getMessage());
        }
    }
    
    private void hitung(){
       if(InputHargaRuang.getText().equals("")){  
       double total,harga,jumlah;
        harga=Double.parseDouble(InputHargaRuang.getText());
        jumlah=Double.parseDouble(InputJumlah.getText());
        total=jumlah+harga;
        String xtotal=Double.toString(total);
        InputTotalBiaya.setText(xtotal);

        }else {
             double total,harga,jumlah,ruang;
        harga=Double.parseDouble(InputHargaRuang.getText());
        jumlah=Double.parseDouble(InputJumlah.getText());
        ruang=Double.parseDouble(InputHargaRuang.getText());
        total=jumlah+harga+ruang;
        String xtotal=Double.toString(total);
        InputTotalBiaya.setText(xtotal);
        }
    }
}
