/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package klinikbersalinjavaapp;

import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Farkhanz
 */
public class Transaksi extends javax.swing.JFrame {

    // Code function atur tanggal    
    java.util.Date saatini = new java.util.Date();
    private SimpleDateFormat simpdafo = new SimpleDateFormat("dd MMMMMMMMM yyyy", Locale.getDefault());
    private String tanggal = simpdafo.format(saatini);
    private Connection conn;
    private Statement state;
    /**
     * Creates new form Transaksi
     */
    public Transaksi() {
        initComponents();
        setLocationRelativeTo(this);
        TglSaatIni.setText(tanggal);
        setJam();
    }
    
        // Code function atur waktu   
        public final void setJam(){
        ActionListener taskPerformer = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String jam = "", menit = "", detik = "";
                
                java.util.Date Waktu = new java.util.Date();
                int set_jam = Waktu.getHours();
                int set_menit = Waktu.getMinutes();
                int set_detik = Waktu.getSeconds();
                
                if(set_jam <= 9) jam= "0";
                if(set_menit <= 9) menit= "0";
                if(set_detik <= 9) detik= "0";
                
                String hours = jam + Integer.toString(set_jam);
                String minutes = menit + Integer.toString(set_menit);
                String seconds = detik + Integer.toString(set_detik);
                
                wkt1.setText(hours+":"+minutes+":"+seconds);
            }
        };
        new Timer(1000, taskPerformer).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane2 = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        InputNoPeriksa = new javax.swing.JTextField();
        InputNoRekamMedis = new javax.swing.JTextField();
        InputNamaPasien = new javax.swing.JTextField();
        InputKodeTindakan = new javax.swing.JTextField();
        CariNoPeriksa = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        InputKodeObat = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        InputNoTransaksi = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        SimpanTransaksi = new javax.swing.JButton();
        BatalTransaksi = new javax.swing.JButton();
        KeluarTransaksi = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        InputNamaAdmin = new javax.swing.JTextField();
        ComboId = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        InputTotalBiaya = new javax.swing.JTextField();
        InputPembayaran = new javax.swing.JTextField();
        InputKembalian = new javax.swing.JTextField();
        TanggaLabel2 = new javax.swing.JLabel();
        TglSaatIni = new javax.swing.JLabel();
        WaktuLabel2 = new javax.swing.JLabel();
        wkt1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Transaksi Pembayaran");
        jDesktopPane2.add(jLabel2);
        jLabel2.setBounds(180, 0, 354, 42);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel4.setText("No Periksa");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel5.setText("No Rekam Medis");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel6.setText("Nama Pasien");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel9.setText("Kode Tindakan");

        InputNoPeriksa.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        InputNoPeriksa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputNoPeriksaActionPerformed(evt);
            }
        });
        InputNoPeriksa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                InputNoPeriksaKeyTyped(evt);
            }
        });

        InputNoRekamMedis.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        InputNoRekamMedis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputNoRekamMedisActionPerformed(evt);
            }
        });

        InputNamaPasien.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        InputKodeTindakan.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        CariNoPeriksa.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        CariNoPeriksa.setText("Cari");
        CariNoPeriksa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CariNoPeriksaActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel11.setText("Kode Obat");

        InputKodeObat.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel7.setText("No_Transaksi");

        InputNoTransaksi.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        InputNoTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputNoTransaksiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(InputNoRekamMedis, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(InputKodeObat)
                            .addComponent(InputKodeTindakan)
                            .addComponent(InputNamaPasien)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel10))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7)))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(InputNoPeriksa, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(InputNoTransaksi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CariNoPeriksa, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputNoTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputNoPeriksa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CariNoPeriksa)
                    .addComponent(jLabel4))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputNoRekamMedis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputNamaPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputKodeTindakan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputKodeObat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(11, 11, 11)
                .addComponent(jLabel10))
        );

        SimpanTransaksi.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        SimpanTransaksi.setText("Simpan");
        SimpanTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanTransaksiActionPerformed(evt);
            }
        });

        BatalTransaksi.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BatalTransaksi.setText("Batal");
        BatalTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BatalTransaksiActionPerformed(evt);
            }
        });

        KeluarTransaksi.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        KeluarTransaksi.setText("Keluar");
        KeluarTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarTransaksiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(SimpanTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BatalTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(KeluarTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BatalTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SimpanTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(KeluarTransaksi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel12.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel12.setText("Id");

        jLabel14.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel14.setText("Nama Admin");

        InputNamaAdmin.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        ComboId.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        ComboId.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "== Pilih ID ==", "A-0001", "A-0002", "A-0003", "A-0004", "A-0005" }));
        ComboId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14))
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(InputNamaAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboId, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(ComboId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputNamaAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        jLabel17.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel17.setText("Total Biaya");

        jLabel18.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel18.setText("Pembayaran");

        jLabel19.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel19.setText("Kembalian");

        InputTotalBiaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputTotalBiayaActionPerformed(evt);
            }
        });
        InputTotalBiaya.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                InputTotalBiayaKeyReleased(evt);
            }
        });

        InputPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputPembayaranActionPerformed(evt);
            }
        });
        InputPembayaran.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                InputPembayaranKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(InputPembayaran, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(InputKembalian, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(InputTotalBiaya, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(30, 30, 30))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(InputTotalBiaya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(InputPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(InputKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TanggaLabel2.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        TanggaLabel2.setText("Tanggal :");

        TglSaatIni.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        TglSaatIni.setText("Tanggal :");

        WaktuLabel2.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        WaktuLabel2.setText("Waktu :");

        wkt1.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        wkt1.setText("Waktu :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(26, 26, 26))
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TanggaLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TglSaatIni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(WaktuLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(wkt1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wkt1)
                    .addComponent(TglSaatIni)
                    .addComponent(WaktuLabel2)
                    .addComponent(TanggaLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InputNoPeriksaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputNoPeriksaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputNoPeriksaActionPerformed

    private void InputNoPeriksaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InputNoPeriksaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_InputNoPeriksaKeyTyped

    private void InputNoRekamMedisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputNoRekamMedisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputNoRekamMedisActionPerformed

    private void InputNoTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputNoTransaksiActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            com.mysql.jdbc.Connection conn = (com.mysql.jdbc.Connection) DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/klinik_db", "root", "");
            com.mysql.jdbc.Statement state = (com.mysql.jdbc.Statement) conn.createStatement();
            String sql = "SELECT * FROM pembayaran order by no_trans";
            ResultSet view = state.executeQuery(sql);
            if (view.first() == false) {
                InputNoTransaksi.setText("000001");
            } else {
                view.last();
                int no = view.getInt(1) + 1;
                String cno=String.valueOf(no);
                int pjg_cno=cno.length();
                for (int i=0;i<3-pjg_cno;i++)
                {
                cno="0"+cno;
                }
                InputNoTransaksi.setText("000"+cno);

            }
            state.close();
            conn.close();
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Eror:" + e, "Gagal", JOptionPane.WARNING_MESSAGE);
//System.err.println("Exception: "+e.getMessage());
        }
    }//GEN-LAST:event_InputNoTransaksiActionPerformed

    private void BatalTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BatalTransaksiActionPerformed
        // TODO add your handling code here:
        InputNoPeriksa.setText("");
        InputNoRekamMedis.setText("");
        InputNamaPasien.setText("");
        InputKodeTindakan.setText("");
        InputNamaAdmin.setText("");
        InputKodeObat.setText("");
        InputPembayaran.setText("");
        InputTotalBiaya.setText("");
        InputKembalian.setText("");
    }//GEN-LAST:event_BatalTransaksiActionPerformed

    private void KeluarTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarTransaksiActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_KeluarTransaksiActionPerformed

    private void ComboIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboIdActionPerformed
        // TODO add your handling code here:
        String id = (String) ComboId.getSelectedItem();
        try
        {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection koneksi = (Connection) DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/rumahbersalin", "root", "");
            Statement statement = (Statement) koneksi.createStatement();
            String sql="SELECT * FROM admin where id like '"+id+"'";
            ResultSet rs = statement.executeQuery(sql);
            if (rs.next())
            {
                InputNamaAdmin.setText(rs.getString(2));
            }
            else {
                JOptionPane.showMessageDialog(null, "Data Tidak Ada");
            } } catch (Exception e){ }
            InputPembayaran.requestFocus();
    }//GEN-LAST:event_ComboIdActionPerformed

    private void InputTotalBiayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputTotalBiayaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_InputTotalBiayaActionPerformed

    private void InputTotalBiayaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InputTotalBiayaKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10){
            InputPembayaran.requestFocus();}
    }//GEN-LAST:event_InputTotalBiayaKeyReleased

    private void InputPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputPembayaranActionPerformed
        // TODO add your handling code here:
        double xkem,xby,xbyr;
        xby=Double.parseDouble(InputTotalBiaya.getText());
        xbyr=Double.parseDouble(InputPembayaran.getText());
        xkem=xbyr-xby;
        String xkembalian=Double.toString(xkem);
        InputKembalian.setText(xkembalian);
    }//GEN-LAST:event_InputPembayaranActionPerformed

    private void InputPembayaranKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InputPembayaranKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10){
            InputKembalian.requestFocus();}
    }//GEN-LAST:event_InputPembayaranKeyReleased

    private void CariNoPeriksaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CariNoPeriksaActionPerformed
        String no_per = InputNoPeriksa.getText();
        try
        {
        Class.forName("com.mysql.jdbc.Driver").newInstance();
        com.mysql.jdbc.Connection conn = (com.mysql.jdbc.Connection) DriverManager.getConnection(
        "jdbc:mysql://localhost:3306/klinik_db", "root", "");
        com.mysql.jdbc.Statement state = (com.mysql.jdbc.Statement) conn.createStatement();
        String sql="SELECT * FROM periksa WHERE no_per like '"+no_per+"'";
         ResultSet view = state.executeQuery(sql);
        if (view.next())
        {
        InputNoRekamMedis.setText(view.getString(5));
        InputNamaPasien.setText(view.getString(6));
        InputKodeTindakan.setText(view.getString(7));
        InputKodeObat.setText(view.getString(15));
        InputTotalBiaya.setText(view.getString(16));

        JOptionPane.showMessageDialog(null, "Data ditemukan","Informasi",JOptionPane.INFORMATION_MESSAGE);
        InputTotalBiaya.requestFocus();
        }
        else
        {
        JOptionPane.showMessageDialog(null, "Data tidak ditemukan ","Informasi",JOptionPane.INFORMATION_MESSAGE);
        }
        state.close();
        conn.close();
        }
        catch ( ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e)
        {
        JOptionPane.showMessageDialog(null, "Eror:"+e,"Gagal",JOptionPane.WARNING_MESSAGE);
        //System.err.println("Exception: "+e.getMessage());
        }
    }//GEN-LAST:event_CariNoPeriksaActionPerformed

    private void SimpanTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanTransaksiActionPerformed
        String no_trans = InputNoTransaksi.getText();
        String no_per = InputNoPeriksa.getText();
        String tanggal = TglSaatIni.getText();
        String jam = wkt1.getText();
        String no_rm = InputNoRekamMedis.getText();
        String nama = InputNamaPasien.getText();
        String kd_tin = InputKodeTindakan.getText();
        String kode = InputKodeObat.getText();
        String id = (String) ComboId.getSelectedItem();
        String tot_bayar = InputTotalBiaya.getText();
        String bayar = InputPembayaran.getText();
        String kembalian = InputKembalian.getText();
        {
        try
        {
        Class.forName("com.mysql.jdbc.Driver").newInstance();
        com.mysql.jdbc.Connection conn = (com.mysql.jdbc.Connection) DriverManager.getConnection(
        "jdbc:mysql://localhost:3306/klinik_db", "root", "");
        com.mysql.jdbc.Statement state = (com.mysql.jdbc.Statement) conn.createStatement();
        String sql="insert into pembayaran values('"+no_trans+"','"+no_per+"','"+tanggal+"','"+jam+"','"+no_rm+"','"+nama+"','"+kd_tin+"','"+kode+"','"+id+"','"+tot_bayar+"','"+bayar+"','"+kembalian+"')";
        int executeUpdate = state.executeUpdate(sql);
        state.close();
        JOptionPane.showMessageDialog(null, "Data berhasil dimasukkan..","Insert Data",JOptionPane.INFORMATION_MESSAGE);
        InputNoPeriksa.setText("");
                InputNoRekamMedis.setText("");
                InputNamaPasien.setText("");
                InputKodeTindakan.setText(""); 
                InputNamaAdmin.setText("");       
                InputKodeObat.setText("");
                InputTotalBiaya.setText("");
                InputPembayaran.setText("");
                InputKembalian.setText("");
        conn.close();
        }
        catch (     ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e)
        {
        JOptionPane.showMessageDialog(null, "Eror: "+e,"Gagal",JOptionPane.WARNING_MESSAGE);
        //System.err.println("Exception: "+e.getMessage());
        }
            }
    }//GEN-LAST:event_SimpanTransaksiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BatalTransaksi;
    private javax.swing.JButton CariNoPeriksa;
    private javax.swing.JComboBox ComboId;
    private javax.swing.JTextField InputKembalian;
    private javax.swing.JTextField InputKodeObat;
    private javax.swing.JTextField InputKodeTindakan;
    private javax.swing.JTextField InputNamaAdmin;
    private javax.swing.JTextField InputNamaPasien;
    private javax.swing.JTextField InputNoPeriksa;
    private javax.swing.JTextField InputNoRekamMedis;
    private javax.swing.JTextField InputNoTransaksi;
    private javax.swing.JTextField InputPembayaran;
    private javax.swing.JTextField InputTotalBiaya;
    private javax.swing.JButton KeluarTransaksi;
    private javax.swing.JButton SimpanTransaksi;
    private javax.swing.JLabel TanggaLabel2;
    private javax.swing.JLabel TglSaatIni;
    private javax.swing.JLabel WaktuLabel2;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel wkt1;
    // End of variables declaration//GEN-END:variables
}
